coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
