help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage
	rm -f .coverage.ma*
	rm -rf .cache
	rm -rf .mypy_cache

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

lint: ## Run linting checks
	./scripts/lint.sh

coverage: ## Run tests with coverage analysis
	python ./scripts/run_coverage.py

deploy: ## Deploy package to PyPI
	./scripts/deploy.sh

build-docs: ## Generate HTML documentation
	./scripts/build_docs.sh

build-changelog: ## Generate changelog.rst from CHANGELOG.md
	python ./scripts/generate_changelog.py

build-api-reference: ## Generate API reference documentation
	python ./scripts/generate_api_reference.py docs/api_reference.rst

build-readme: ## Build README.rst from template
	python ./scripts/build_readme.py
